// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-eZb82KnCnGh9-sSqaHcyVSwcB7WDbEc',
    appId: '1:969641690633:web:b3e11cb657b5d233d1dad8',
    messagingSenderId: '969641690633',
    projectId: 'farefinale-4ec3b',
    authDomain: 'farefinale-4ec3b.firebaseapp.com',
    storageBucket: 'farefinale-4ec3b.appspot.com',
    measurementId: 'G-MYJMTP53T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTkhm30Y4yZSTS92eKlopfqEDDgXwZkgE',
    appId: '1:969641690633:android:67056784efb3b095d1dad8',
    messagingSenderId: '969641690633',
    projectId: 'farefinale-4ec3b',
    storageBucket: 'farefinale-4ec3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJvvaLRVxey1f9NtF_iW4QIw0MPU3624',
    appId: '1:969641690633:ios:73bae0494be13f32d1dad8',
    messagingSenderId: '969641690633',
    projectId: 'farefinale-4ec3b',
    storageBucket: 'farefinale-4ec3b.appspot.com',
    iosBundleId: 'com.example.farefinale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJvvaLRVxey1f9NtF_iW4QIw0MPU3624',
    appId: '1:969641690633:ios:73bae0494be13f32d1dad8',
    messagingSenderId: '969641690633',
    projectId: 'farefinale-4ec3b',
    storageBucket: 'farefinale-4ec3b.appspot.com',
    iosBundleId: 'com.example.farefinale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-eZb82KnCnGh9-sSqaHcyVSwcB7WDbEc',
    appId: '1:969641690633:web:f85f56fb58e603d9d1dad8',
    messagingSenderId: '969641690633',
    projectId: 'farefinale-4ec3b',
    authDomain: 'farefinale-4ec3b.firebaseapp.com',
    storageBucket: 'farefinale-4ec3b.appspot.com',
    measurementId: 'G-VTDNM096K2',
  );

}